routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('home');
Route::get('posts','PostController@index')->name('post.index');
Route::get('post/{slug}','PostController@details')->name('post.details');

Route::get('category/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('tag/{slug}','PostController@postByTag')->name('tag.posts');

Route::get('author/profile/{username}','AuthorController@profile')->name('author.profile');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');

Route::get('search','SearchController@search')->name('search');


Route::get('aboutus',function(){
	return view('aboutMe');

});


Auth::routes();
Route::group(['middleware'=>['auth']], function(){
	Route::post('favorite/add/{post}','FavoriteController@add')->name('post.favorite');
	Route::post('comment/{post}','CommentController@store')->name('comment.store');

});



Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){
	Route::get('dashbord','DashbordController@index')->name('dashbord');

	Route::get('settings','SettingsController@index')->name('settings');
	Route::put('profile-update','SettingsController@updateProfile')->name('profile.update');
	Route::put('password-update','SettingsController@updatePassword')->name('password.update');

	Route::resource('tag','TagController');
	Route::resource('category','CategoryController');
	Route::resource('post','PostController');

	Route::get('/pending/post','PostController@pending')->name('post.pending');
	Route::put('/post/approve/{id}','PostController@approve')->name('post.approve');


	Route::get('/favorite','FavoriteController@index')->name('favorite.index');

	Route::get('authors','AuthorController@index')->name('author.index');
	Route::delete('author/{id}','AuthorController@destroy')->name('author.destroy');

	Route::get('comments','CommentController@index')->name('comment.index');
	Route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');


	Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
	Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');
});





Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth','author']],function(){
	Route::get('dashbord','DashbordController@index')->name('dashbord');

	Route::get('comments','CommentController@index')->name('comment.index');
	Route::delete('comments/{id}','CommentController@destroy')->name('comment.destroy');

	Route::get('settings','SettingController@index')->name('settings');
	Route::put('profile-update','SettingController@updateProfile')->name('profile.update');
	Route::put('password-update','SettingController@updatePassword')->name('password.update');

	Route::resource('post','PostController');


	Route::get('/favorite','FavoriteController@index')->name('favorite.index');
});


View::composer('layouts.frontend.partial.footer',function($view){
	$categories = App\Category::all();
	$view->with('categories',$categories);
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\User;
use Brian2694\Toastr\Facades\Toastr;

class AuthorController extends Controller
{
    public function index(){
    	$authors = User::authors()
    			->withCount('posts')
    			->withCount('comments')
    			->withCount('favorite_posts')
    			->get();
    	return view('admin.authors',compact('authors'));
    }
    public function destroy($id){
    	User::findOrFail($id)->delete();
    	Toastr::success('Author Successfully Delete :)','Success');
    	return redirect()->back();
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Post;
use App\Category;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Auth;

// notification
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use Illuminate\Support\Facades\Notification;
use App\Subscriber;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        return view('admin.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.create',compact('categories','tags')); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'required',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
        ]);

        $image = $request->file('image');
        $slug = str::slug($request->title);
        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }

            Image::make($image)->resize(1600,1066)->save('storage/post/'.$imageName);
        }else{
            $imageName = 'default.png';
        }

        $post = new Post();
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = $slug;
        $post->image = $imageName;
        $post->body = $request->body;
        if (isset($request->status)) {
            $post->status = true;
        }else{
            $post->status = false;
        }
        $post->is_approved = true;
        $post->save();
        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

   // subscriber send mail
        $subscribers = Subscriber::all();
        foreach ($subscribers as $key => $subscriber) {
            Notification::route('mail', $subscriber->email)
            ->notify(new NewPostNotify($post));
        }

        Toastr::success('Post Successfully Save :=)','Success');
        return redirect()->route('admin.post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)   
    {
       //find korte hobena ..model use kora asea.php artisan make:controller --model=Post deoyar karone aa post model niaaaa dada tule anea $post variable a rakhsea
   
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.post.edit',compact('post','categories','tags')); 
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'image',
            'categories'=>'required',
            'tags'=>'required',
            'body'=>'required',
        ]);

        $image = $request->file('image');
        $slug = str::slug($request->title);
        if (isset($image)) {
            $currentDade = Carbon::now()->toDateString();
            $imageName = $slug.'-'.$currentDade.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }
            // delete old image
            if (Storage::disk('public')->exists('post/'.$post->image)) {
                Storage::disk('public')->delete('post/'.$post->image);
            }

            Image::make($image)->resize(1600,1066)->save('storage/post/'.$imageName);
        }else{
            $imageName = $post->image;
        }

        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = $slug;
        $post->image = $imageName;
        $post->body = $request->body;
        if (isset($request->status)) {
            $post->status = true;
        }else{
            $post->status = false;
        }
        $post->is_approved = true;
        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);
        Toastr::success('Post Successfully Updated :=)','Success');
        return redirect()->route('admin.post.index');
    }
    


    // show pending post all author create
    public function pending(){
        $posts = Post::where('is_approved',false)->get();
        return view('admin.post.pending',compact('posts'));
    }

    // approval function
    public function approve($id){
        $post = Post::find($id);
        if ($post->is_approved == false) {
            $post->is_approved = true;
            $post->save();
            
            // send notification author
            $post->user->notify(new AuthorPostApproved($post));

        // subscriber send mail
             $subscribers = Subscriber::all();
             foreach ($subscribers as $key => $subscriber) {
                  Notification::route('mail', $subscriber->email)
                          ->notify(new NewPostNotify($post));
                   }


            Toastr::success('Post Successfully Approved','Success');
        }else{
            Toastr::info('This Post Already Approved','info');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (Storage::disk('public')->exists('post/'.$post->image)) {
            Storage::disk('public')->delete('post/'.$post->image);
        }

        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();
        Toastr::success('Post Delete Successfully :=)','Success');
        return redirect()->back();
    }
    
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Comment;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;


class CommentController extends Controller
{
    public function index(){
    	$posts = Auth::user()->posts;
    	return view('author.comment',compact('posts'));

    }

    public function destroy($id){
    	$comment = Comment::findOrFail($id);
    	if ($comment->post->user->id == Auth::id()) {
    		$comment->delete();
    	Toastr::success('Comment Delete Successfully','success');
    	}else{
    	Toastr::error('You are not authorized to delete this comment :(','Access Denied !!!');
    	}
    	return redirect()->back();

    }
}

app/Http/Controllers/Author/DashbordController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;

class DashbordController extends Controller
{
    public function index(){
    	$user = Auth::user();
    	$posts = $user->posts;
    	$popular_posts = $user->posts()
    		->withCount('comments')
    		->withCount('favorite_to_users')
    		->orderBy('view_count','desc')
    		->orderBy('comments_count')
    		->orderBy('favorite_to_users_count')
    		->take(5)->get();
    	$total_pandding_posts = $posts->where('is_approved',false)->count();
    	$all_views = $posts->sum('view_count');
    	return view('author.dashbord',compact('posts','popular_posts','total_pandding_posts','all_views'));
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FavoriteController extends Controller
{
    public function index(){
		$posts = Auth::user()->favorite_posts;

		return view('author.favorite',compact('posts'));
	}
}

app/Http/Controllers/Author/SettingController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Str;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Hash;

class SettingController extends Controller
{
     public function index(){
    	return view('author.settings');
    }


    public function updateProfile(Request $request){
    	$this->validate($request,[
    		'name' => 'required',
    		'email' => 'required|email',
    		'image' => 'required|image',
    	]);

    	$image = $request->file('image');
    	$slug = str::slug($request->name);
    	$user = User::findOrfail(Auth::id());
    	if (isset($image)) {
    		$currentDate = Carbon::now()->toDateString();
    		$imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

    		if (!Storage::disk('public')->exists('profile')) {
                Storage::disk('public')->makeDirectory('profile');
            }
            if (Storage::disk('public')->exists('profile/'.$user->image)) {
                Storage::disk('public')->delete('profile/'.$user->image);
            }
            Image::make($image)->resize(500,500)->save('storage/profile/'.$imageName);
    	}else{
    		$imageName = $user->image;
    	}

    	$user->name = $request->name;
    	$user->email = $request->email;
    	$user->image = $imageName;
    	$user->about = $request->about;
    	$user->save();

    	Toastr::success('Profile Update Successfully :=) ','success');
    	return redirect()->back();
    }



    // update admin  password
public function updatePassword(Request $request){
	$this->validate($request,[
		'old_password' => 'required',
		'password' => 'required|confirmed'
	]);

	$hashedPassword = Auth::user()->password;
	if (Hash::check($request->old_password,$hashedPassword)) {
		if (!Hash::check($request->password,$hashedPassword)) {
			$user = User::find(Auth::id());
			$user->password = Hash::make($request->password);
			$user->save();
			Auth::logout();
			return redirect()->back();
		}else{

			Toastr::error('New Password Cannot Be The Same As Old Password','Error');
			return redirect()->back();
		}
	}else{
		Toastr::error('Current/Old Password Not Match','Error');
		return redirect()->back();
	}
}

}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;

class AuthorController extends Controller
{
	public function profile($username){
		$author = User::where('userName',$username)->first();
		$posts = $author->posts()->approved()->published()->get();
		return view('profile',compact('author','posts'));
	}
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;

use Illuminate\Support\Facades\Session;

class PostController extends Controller
{
	public function index(){
		$posts = Post::latest()->approved()->published()->paginate(12);
		return view('posts',compact('posts'));
	}


    public function details($slug){
    	$post = Post::where('slug',$slug)->approved()->published()->first();

    	// view count
    	$blogKey = 'blog_' . $post->id;
    	if (!Session::has($blogKey)) {
    		$post->increment('view_count');
    		Session::put($blogKey,1);
    	}

    	$randomposts = Post::approved()->published()->take(3)->inRandomOrder('3')->get();
    	return view('post',compact('post','randomposts'));

    }


    public function postByCategory($slug){
        $category = Category::where('slug',$slug)->first();
        $posts = $category->posts()->approved()->published()->get();
       return view('category',compact('category','posts'));
    }


    public function postByTag($slug){
        $tag = Tag::where('slug',$slug)->first();
        $posts = $tag->posts()->approved()->published()->get();
       return view('tag',compact('tag','posts'));
    }
}

resources/views/author/post/index.blade.php
@extends('layouts.backend.app')

@section('title','post')


@push('css')
<!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">

@endpush




@section('contain')
        <div class="container-fluid">
            <div class="block-header">
                <a class="btn btn-primary waves-effect" href="{{route('author.post.create')}}">
                	<i class="material-icons">add</i>
                	<span>Add New Post</span>
            	</a>
            </div>
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                    ALL Post
                                    <span class="badge bg-blue">{{$posts->count() }}</span>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Author</th>
                                            <th><i class="material-icons">visibility</i></th>
                                            <th>Is Approve</th>
                                            <th>Status</th>
                                            <th>Created At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Author</th>
                                            <th><i class="material-icons">visibility</i></th>
                                            <th>Is Approve</th>
                                            <th>Status</th>
                                            <th>Created At</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($posts as $key=>$post)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td>{{ Illuminate\Support\Str::limit($post->title, 15, $end='....') }}</td>
                                                <td>{{ $post->user->name }}</td>
                                                <td>{{ $post->view_count }}</td>
                                                <td>
                                                    @if($post->is_approved == true)
                                                     <span class="badge bg-blue">Approved</span>
                                                     @else
                                                     <span class="badge bg-pink">Pending</span>
                                                    @endif
                                                </td>
                                                <td>
                                                    @if($post->status == true)
                                                     <span class="badge bg-blue">Publish</span>
                                                     @else
                                                     <span class="badge bg-pink">Pending</span>
                                                    @endif
                                                </td>
                                                <td>{{ $post->created_at }}</td>
                                                <td class="text-center">
                                                    <a href="{{route('author.post.show',$post->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">visibility</i>
                                                    </a>
                                                    <a href="{{route('author.post.edit',$post->id)}}" class="btn btn-info waves-effect">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <button class="btn btn-danger waves-effect" type="button"
                                                    onclick="deletePost({{ $post->id}})">
                                                        <i class="material-icons">delete</i>
                                                    </button>
                                                    <form id="delete-form-{{ $post->id}}" action="{{ route('author.post.destroy',$post->id)}}" method="POST" style="display: none;">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
@endsection




@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>

    <!-- alart masage -->
    <script src="{{asset('assets/backend/sweetalert/sweetalert.min.js')}}"></script>

    <script type="text/javascript">
        function deletePost(id){
                const swalWithBootstrapButtons = Swal.mixin({
                  customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                  },
                  buttonsStyling: false
                })

                swalWithBootstrapButtons.fire({
                  title: 'Are you sure?',
                  text: "You won't be able to revert this!",
                  icon: 'warning',
                  showCancelButton: true,
                  confirmButtonText: 'Yes, delete it!',
                  cancelButtonText: 'No, cancel!',
                  reverseButtons: true
                }).then((result) => {
                  if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                  } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                  ) {
                    swalWithBootstrapButtons.fire(
                      'Cancelled',
                      'Your imaginary file is safe :)',
                      'error'
                    )
                  }
                })

                     }
    </script>


@endpush

resources/views/author/post/show.blade.php
@extends('layouts.backend.app')

@section('title','show')

@push('css')

@endpush

@section('contain')
        <div class="container-fluid">
            <a href="{{route('author.post.index')}}" class="btn btn-danger waves-effect">Back</a>
            @if($post->is_approved == false)
               <button type="button" class="btn btn-success pull-right">
                   <i class="material-icons">done</i>
                   <span>Approv</span>
               </button>
            @else
               <button type="button" class="btn btn-success pull-right" disabled>
                   <i class="material-icons">done</i>
                   <span>Approved</span>
               </button>
            @endif
            <br>
            <br>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{$post->title}}
                                <small>Posted By <strong><a href="" title="profile link">{{$post->user->name}}</a></strong> On {{$post->created_at->toFormattedDateString()}} </small>
                            </h2>
                        </div>
                        <div class="body">
                                {!! $post->body !!}

                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-cyan">
                            <h2>
                                Categories
                            </h2>
                        </div>
                        <div class="body">
                            <!--relationship categories function post model theke category model ar data neya jay-->
                         @foreach($post->categories as $category) 
                            <span class="label bg-cyan">{{$category->name}}</span>
                         @endforeach
                        </div>
                    </div>
                    <div class="card">
                        <div class="header bg-green">
                            <h2>
                                Tags
                            </h2>
                        </div>
                        <div class="body">
                            <!--relationship categories function post model theke category model ar data neya jay-->
                         @foreach($post->tags as $tag) 
                            <span class="label bg-green">{{$tag->name}}</span>
                         @endforeach
                        </div>
                    </div>
                    <div class="card">
                        <div class="header bg-amber">
                            <h2>
                                Feature Image
                            </h2>
                        </div>
                        <div class="body">
                            <img class="img-responsive thumbnail" src="{{Storage::disk('public')->url('post/'.$post->image)}}" alt="">
                        </div>
                    </div>
                </div>
            </div> 
        </div>
@endsection

@push('js')
<!-- Select Plugin Js -->
    <script src="{{asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>
<!-- TinyMCE -->
    <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>

    <script type="text/javascript">
        $(function () {
    //TinyMCE
    tinymce.init({
        selector: "textarea#tinymce",
        theme: "modern",
        height: 300,
        plugins: [
            'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
        ],
        toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons',
        image_advtab: true
    });
    tinymce.suffix = ".min";
    tinyMCE.baseURL = '{{asset('assets/backend/plugins/tinymce')}}';
});
    </script>
@endpush